insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Users
    path('users/', include('users.urls')),

    # Posts
    path('', include('posts.urls', namespace="posts")),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.views import *

app_name = "posts"
urlpatterns = [
    path('', PostFeedView.as_view(), name='feed'),
    path('posts/new/', CreatePostView.as_view(), name='create_post'),
    path('posts/<pk>/', PostDetailView.as_view(), name='detail'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required


from users.views import *

app_name = "users"
urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<pk>/update', UpdateProfileView.as_view(), name='update_profile'),
    path('<pk>', login_required(UserDetailView.as_view()), name='detail'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    caption = models.CharField(max_length=255, primary_key=True, default=' ')
    photo = models.ImageField(upload_to='posts/photos')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.caption

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(upload_to='users/pictures', default='users/pictures/default-profile.png', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

posts/forms.py
"""Posts forms"""

# Django
from django import forms

# Models
from posts.models import Post


class PostForm(forms.ModelForm):
	"""Post model form"""

	class Meta:
		"""Form settings."""
		model = Post
		fields = ['caption', 'photo']

users/forms.py
"""Users forms"""

# Django
from django import forms

# Models
from users.models import Profile
from django.contrib.auth.models import User


class SignupForm(forms.ModelForm):
    username = forms.CharField(label='Username', min_length=5, max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(label='Password', min_length=8, max_length=15, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    first_name = forms.CharField(label='First Name', min_length=2, max_length=20, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(label='Last Name', min_length=2, max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    email = forms.CharField(label='Email', min_length=5, max_length=40, widget=forms.EmailInput(attrs={'placeholder': 'Email'}))

    class Meta:
    	model = User
    	fields = ['username', 'password', 'first_name', 'last_name', "email"]

class UpdateForm(forms.ModelForm):
    class Meta:
    	model = Profile
    	fields = ['website', 'biography', 'phone_number', 'picture']

posts/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.urls import reverse_lazy

# Models
from posts.models import Post

# Forms
from posts.forms import PostForm


class CreatePostView(generic.CreateView):
    # the view to create a post
    template_name = 'posts/new.html'      # set the template name to create a new post
    form_class = PostForm          # set the form where the person can create a post
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        # get the context data
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        # save the data from the form
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostFeedView(generic.ListView):
    # the view to display all the posts in the feed
    model = Post                # set the model as Post
    template_name = 'posts/feed.html'   # set the template to display the feed
    context_object_name = 'posts'    # set the context object name to posts to use in the template
    ordering = ('-created',)        # order the photos from earlier to latest created
    paginate_by = 4             # set the pagination to 4 posts a page

class PostDetailView(generic.DetailView):
    # the view to display a post
    model = Post            # set the model as Post
    template_name = 'posts/detail.html'     # set the template to display the details of the post

users/views.py
from django.http import HttpResponse
from django.contrib.auth import logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.models import User

# Models
from users.models import Profile
from posts.models import Post

# Forms
from users.forms import SignupForm, UpdateForm

class SignupView(generic.CreateView):
    # the view to create a user
    template_name = 'users/signup.html'         # set the template name to signup
    form_class = SignupForm                     # set the form where the person can create a user
    success_url = reverse_lazy('users:login')   # set the url that the page will redirect to when the form is submitted

    def form_valid(self, form):
        # function to save the form data
        user = form.save(commit=False)             # get the user
        password = form.cleaned_data['password']   # get the password

        user.set_password(password)                # set the password for the new user
        user.save()                                # save the new user
        Profile.objects.create(user=user)          # create a new profile that is linked to the new user

        return super(SignupView, self).form_valid(form)   # return the saved data

    def form_invalid(self, form):
        # return an HttpResponse if the form is invalid
        return HttpResponse("The form is invalid")

class LoginView(auth_views.LoginView):
    # the view to log a user in
    template_name = 'users/login.html'       # set the template name to login
    redirect_authenticated_user = True       # redirects user if/when authenticated


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    # the view to log a user out
    """ Nothing is needed in this function """

class UpdateProfileView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'users/update_profile.html'     # set the template name to update
    form_class = UpdateForm               # set the form where the person can update their profile
    model = Profile         # set the model as Profile because that is what is being updated

    def get_success_url(self, **kwargs):
        # returns the url to go to when the form is submitted
        return reverse('users:detail', kwargs={'pk': self.object.user.pk})

class UserDetailView(generic.DetailView):
    # the view to see the profile details
    model = Profile         # set the model as Profile because that is what is being displayed
    template_name = 'users/detail.html'         # set the template name to display the profile details

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        # geth the context
        user_name = self.get_object()           # get the username of the user
        user = User.objects.get(username=user_name) # get the user with that username
        context['user'] = user          # add the user to the context
        context['posts'] = Post.objects.filter(user=user).order_by('-created') # add the user's posts to the context
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<!-- Icons -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">

		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

		{% block head_content %}
		{% endblock head_content %}

	</head>
	<body>
		{% if user.is_authenticated %}
	  	{% include "nav.html" %}
		{% endif %}
    <div class="container">
       {% block container %}
       {% endblock%}
    </div>

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg static-top navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "posts:feed" %}">
      <img src="{% static "img/instagram.jpg" %}" alt="Instagram" height="90"/>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#instagramNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="instagramNav">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
          <a href="{% url "users:detail" user.pk %}">
            <i class="fas fa-user-circle"></i>
            <span>View Profile</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url "posts:create_post" %}">
            <i class="fas fa-plus mr-1"></i>
            <span>Add Post</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url "users:logout" %}">
            <i class="fas fa-sign-out-alt mr-1"></i>
            <span>Log Out</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/pagination.html
<nav class=mt-5>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link text-dark" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    </li>
    {% endif %}
    <li class="page-item">
      <a class="page-link text-dark" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
    </li>
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link text-dark" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>{{ post.caption }} | Instagram</title>
{% endblock %}

{% block container %}

{% if user.is_authenticated %}
  <div class="container">
    <div class="row">
      {% include 'posts/post_card.html' %}
    </div>
  </div>
{% else %}
  {% include 'users/logged_out.html' %}
{% endif %}

{% endblock %}

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
  <title>Instagram Feed</title>
{% endblock%}

{% block container %}
  <div class="container">
    {% if user.is_authenticated %}
      <div class="row">
        <h1>Instagram Feed!</h1>
        {% for post in posts %}
          {% include 'posts/post_card.html' %}
        {% endfor %}
      </div>
    {% else %}
      {% include 'users/logged_out.html' %}
    {% endif %}
  </div>
  {% if user.is_authenticated %}
    {% include 'pagination.html' %}
  {% endif %}
{% endblock %}

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create New Post</title>
{% endblock %}

{% block container %}
  {% if user.is_authenticated %}
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="card mx-auto mt-5" style="width: 600px;">
          <div class="card-body">
            <h4 class="card-title text-center mb-4">Post a new photo!</h4>
            <form method="Post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn">Post</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    {% include 'users/logged_out.html' %}
  {% endif %}
{% endblock %}

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
  <a href="{% url "users:detail" post.user.pk %}">
    <div class="media pt-3 pl-3 pb-1">
      <img class="mr-3 rounded" height="60" src="{{ post.user.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
      <div class="media-body">
        <h5 class="text-dark">@{{ post.user.get_username }}</h5>
      </div>
    </div>
  </a>
  <a href="{% url "posts:detail" post.pk %}">
    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.caption }}">
  </a>
  <div class="p-3 mt-4 border-double border-right-0 border-left-0">
    <span><strong> {{ post.user.get_username }} </strong> - {{ post.caption }} </span>
  </div>
  <div class="m-2">
    <small>{{ post.modified }}</small>
  </div>
</div>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Instagram</title>
{% endblock %}

{% block container %}
  {% if user.is_authenticated %}
    <div class="container">
      <div class="row">
        <div class="col-4 col-sm-4 col-md-3 col-lg-2 col-xl-2">
          <img src="{{ user.profile.picture.url }}" alt="@{{ user.username }}" class="rounded img-fluid" />
        </div>
        <div class="col-8 col-sm-8 col-md-9 col-lg-10 col-xl-10 ">
          <h2 class="mb-3">{{ user.first_name }} {{ user.last_name }}</h2>
          {% if user == request.user %}
            <a href="{% url "users:update_profile" user.pk %}" class="btn btn-sm btn-outline-info">Edit Profile</a>
          {% endif %}
        </div>
        <div class="row mt-3 ml-1">
          <div class="col-12">
            <span>{{ user.profile.biography }}</span>
          </div>
        </div>
      </div>
    </div>
    <hr />
    <div class="container">
      <div class="row">
        {% for post in posts %}
        <div class="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4">
          <a href="{% url "posts:detail" post.pk %}">
            <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid border-double border-dark m-2"/>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  {% else %}
    {% include 'users/logged_out.html' %}
  {% endif %}
{% endblock %}

templates/users/logged_out.html
{% load static %}
<div class="card mx-auto mt-5" style="width: 600px;">
  <img class="card-img-top mx-auto mb-3 mt-3" src="{% static "img/instagram.jpg" %}" alt="Instagram" style="width: 400px;">
  <div class="card-body">
    <h4 class="card-title text-center mb-4">You are logged out</h4>
    <a href="{% url 'users:login' %}" class="btn btn-block" role="button">
      <i class="fas fa-sign-in-alt mr-1"></i>
      <span>Log In</span>
    </a>
    <a href="{% url 'users:signup' %}" class="btn btn-block mt-3" role="button">
      <i class="fas fa-user-plus mr-1"></i>
      <span>Sign Up</span>
    </a>
  </div>
</div>

templates/users/login.html
{% extends "base.html" %}

{% block head_content %}
<title>Login User</title>
{% endblock %}

{% load static %}
{% block container %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card mx-auto mt-5" style="width: 600px;">
        <img class="card-img-top mx-auto mb-3 mt-3" src="{% static "img/instagram.jpg" %}" alt="Instagram" style="width: 400px;">
        <div class="card-body">
          <h4 class="card-title text-center mb-4">Log In</h4>
          <form method="Post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Log In</button>
          </form>
        </div>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}

{% block head_content %}
<title>Create New User</title>
{% endblock %}

{% block container %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card mx-auto mt-5" style="width: 600px;">
        <div class="card-body">
          <h4 class="card-title text-center mb-4">Signup</h4>
          <form method="Post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Create</button>
          </form>
        </div>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}

{% block head_content %}
<title>Update Information</title>
{% endblock %}

{% block container %}
  {% if user.is_authenticated %}
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="card mx-auto mt-5" style="width: 600px;">
          <div class="card-body">
            <h4 class="card-title text-center mb-4">Update Information</h4>
            <form method="Post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn">Update</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    {% include 'users/logged_out.html' %}
  {% endif %}
  {% endblock %}